### PR TITLE
Implement restriction of repo URL depth within hierarchical organisat…

### PR DESCRIPTION
**Pull request by pale3**
…ion.

Brief:
With previous hierarchical style, if there is repo created within nested
projects, or better described as "subprojcts of subprojects", for user to
access it he needs to specify full blown URL to reach repos.

E.g repository: foo.git
http://redmine/projects1/project2/project3/project4/project5/foo.git

This patch implements same hierarchical style but with access to it
by only using <project_identifier>/repo.git

E.g
http://redmine/project5/foo.git

### CODE REVIEW

**Comment by pale3** [comment]
above is PR for #678

**Comment by pale3** [comment]
@n-rodriguez 
feedback please?

**Comment by n-rodriguez** [comment]
Hi! Thanks for your patch! It would have been nice to have some tests that cover those changes.

**Comment by PowerKiKi** [comment]
This old PR is very unlikely to be merged as is. I'll close it for now. If you feel it is still relevant please either rebase on master or create a new PR.

**Pull request closed without merging**
