### PR TITLE
Redmine5 finalization

### PR DESCRIPTION
**Pull request by dosyfier**
With the works of @PowerKiKi and @prahal, I managed to make redmine_git_hosting plugin work with Redmine 5.

Here is a recap of what this PR brings to the existing "redmine5" branch:
* Rails 6 compatibility fixes (done by @prahal);
* Ruby 3.x compatibility fixes, most of which are related to the [Separation of positional and keyword arguments](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) feature;
* Upgrade of gitolite-rugged, which brings a Ruby 3.x compatible version of rugged (see: https://github.com/jbox-web/gitolite-rugged/pull/8);
* a typo fix.

With these changes, here's what I was able to test:
* start a Redmine 5 instance with the redmine_git_hosting plugin,
* browse the redmine_git_hosting settings page,
* register an SSH key into Redmine,
* create / delete a gitolite repository,
* push changes to a gitolite repository and see the result in Redmine afterwards.

Nota: This PR is based upon the work done in following PRs:
* #806 (cherry-picked)
* #807 (cherry-picked)
* #808 (cherry-picked)
* #812 (cherry-picked)
* and of course: #813

### CODE REVIEW

**Comment by PowerKiKi** [comment]
Thanks a lot for this work. I see all tests are still failing when running `bundle exec rake db:test:prepare`. Would you be able to make tests pass, so we can have more confidence that the plugin would still work completely ?

**Comment by dosyfier** [comment]
> Thanks a lot for this work. I see all tests are still failing when running `bundle exec rake db:test:prepare`. Would you be able to make tests pass, so we can have more confidence that the plugin would still work completely ?

Agreed, that's a must have!

I'll work on it. Not sure though how long the build has been broken, but at first look, it looks related to some dependencies (like redmine_sidekiq) not being compatible with Rails 6.

**Comment by PowerKiKi** [comment]
Damned, I accidentally merged the commit into `redmine5` branch, even though the work is not finished yet.

@dosyfier would you mind opening a new (draft) PR with the rest of you work please ?

**Comment by dosyfier** [comment]
Hi @PowerKiKi,
No worries for the merge. Yet, I haven't gone further with the tests to fix.
I think I solved the issue with redmine-sidekiq (thanks for the PR btw). Now I can go to the testing step of the pipeline, but there are lots of tests failing...

It looks like the patches brought by redmine_git_hosting (from the `lib/redmine_git_hosting/patches/` folder) are not loaded at Rails startup. There's some code at the end of `lib/redmine_git_hosting.rb` which purpose is to load these patches:

```ruby
# Set up autoload of patches                                                                                                                                                                                                                                                  
Rails.config.to_prepare do
  # Redmine Git Hosting Libs and Patches
  RedmineGitHosting.load_plugin!

  # Redmine SCM adapter
  require_dependency 'redmine/scm/adapters/xitolite_adapter'

  require 'hrack/bundle'
end
```

but it isn't called at Redmine startup.

I attempted to change `Rails.config.to_prepare` into `Rails.application.config.to_prepare` (my last commit on the PR), but it didn't change anything.

I'm no rails expert, so it may take me some time to investigate, but I'll try again probably next weekend, and hopefully I'll open a new PR :)

**Comment by prahal** [comment]
Not an answer but clues:

in redmine_plugin_loader
```
        def required_lib_dirs
	  plugin_lib_dir plugin_name, '**', '*.rb'
	end

        def plugin_dir(*dirs)
          Rails.root.join('plugins', plugin_name, *dirs)
        end

        def plugin_lib_dir(*dirs)
          plugin_dir('lib', *dirs)
        end

	def load_plugin!
	  autoload_libs!
	  autoload_paths!
	  autoload_locales!
	end


	def autoload_libs!
	  Dir.glob(required_lib_dirs).each do |file|
		require_dependency file unless skip_lib_file? file
	  end
	end
```

```
    def plugin_hooks_dir
      plugin_lib_dir plugin_name, 'hooks'
    end

    def hook_file?(file)
      File.dirname(file) == plugin_hooks_dir.to_s
    end

    def skip_lib_file?(file)
      # Exclude Redmine Views Hooks from Rails loader to avoid multiple calls to hooks on reload in dev environment.
      true if hook_file?(file) || (file.include?('journal_logger.rb') && !Object.const_defined?('Account'))
    end
```

autoload_libs is the function that copes with lib/redmine_git_hosting/ subdirs.
It loads all ruby files in all the subdirs of <plugin>/lib/redmine_git_hosting/ except journal_logger.rb like files when Account is already defined, and except <plugin>/lib/redmine_git_hosting/hooks (the latter do not exists anymore since https://github.com/jbox-web/redmine_git_hosting/commits/master/lib/redmine_git_hosting/hooks ie commit 42017174b4bdb35a0ef3c062fa936ffba6b2a4ff , this is at best a leftover).


As far as I know rails now uses zeitwerk autoloaders which autoload all ruby classes matching their file hierarchy (ie /lib/redmine_git_hosting/test.rb when it contains the definition of RedmineGitHosting::test.rb.

ie from https://guides.rubyonrails.org/autoloading_and_reloading_constants.html
> Rails manages a couple of [Zeitwerk](https://github.com/fxn/zeitwerk) loaders on your behalf.
> In a Rails application file names have to match the constants they define, with directories acting as namespaces.
but also
> Idiomatic Rails applications only issue require calls to load stuff from their lib directory, the Ruby standard library, Ruby gems, etc. That is, anything that does not belong to their autoload paths, explained below.

I did add <plugin>/lib to the autoloader path in my patchset. You might want to try with the code for that too, ie https://github.com/jbox-web/redmine_git_hosting/pull/807/files#diff-4afdb3c3c34a069c37756ebaee5883f21565d29c7730ba4565b88aa809d226cc . 

https://github.com/haru/redmine_wiki_extensions/commit/91499ccd574a09e3327920b57eb06cf16518e414
ie in the plugin init.rb
`$LOAD_PATH.unshift "#{File.dirname(FILE)}/lib"`
(add plugin lib to search path).


It fixed a:
`LoadError: cannot load such file -- redmine_git_hosting` issue.

**Comment by dosyfier** [comment]
Hi @prahal,
Thanks for the hint.

Actually, your `$LOAD_PATH.unshift "#{File.dirname(FILE)}/lib"` was already added to the plugin's init.rb, but there were still things that weren't loaded. Maybe it's what the `autoload_paths!` function was meant for?

Anyway, I think I managed to make it work with 23d15416fc2f805e8d5e0b9828e99ce13e695ae7.

**Pull request merged**
