### PR TITLE
Redmine 5

### PR DESCRIPTION
**Pull request by PowerKiKi**

### CODE REVIEW

**Comment by PowerKiKi** [comment]
@alexandermeindl, my very naive attempt to test on Redmine 5 failed miserably for a whole lot of reason. By any chance have you upgraded to Redmine 5 already ? or is it something you might be working on soon-ish ?

**Comment by alexandermeindl** [comment]
Hi @PowerKiKi,

no, sorry. I did no work for upgrading to Redmine 5 and currently it is not planned, too.

**Comment by tomhub** [comment]
Hi
It is strange: plugin requires additionals plugin, but additionals seem to require redmine 5. However, redmine_git_hosting is not redmine 5 compatible.. Maybe instructions need to be updated how to pull correct version dependencies for redmine_git_hosting?

**Comment by Alwaysin** [comment]
Hi @PowerKiKi , did you by any chance make it work with Redmine 5 with your latest commits?

@alexandermeindl did you change your mind since June? :)

**Comment by dosyfier** [comment]
Hi,
I carried on your good work, and I'm think I'm pretty close to something fully functional with Redmine 5.
Please have a look to #815.

**Comment by PowerKiKi** [comment]
Superseded by #815

**Comment by PowerKiKi** [comment]
@dosyfier on this branch, which also contains your changes, I get the following error when accessing `/settings/plugin/redmine_git_hosting`. Is it working for you ?

```
Showing /sites/redmine/plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.slim where line #22 raised:

undefined local variable or method `gitolite_plugin_settings_tabs' for #<ActionView::Base:0x0000000001e910>
```

**Comment by dosyfier** [comment]
> @dosyfier on this branch, which also contains your changes, I get the following error when accessing http://localhost:3000/settings/plugin/redmine_git_hosting. Is it working for you ?
> 
> ```
> Showing /sites/redmine/plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.slim where line #22 raised:
> 
> undefined local variable or method `gitolite_plugin_settings_tabs' for #<ActionView::Base:0x0000000001e910>
> ```

No, I didn't get that one (and I was able to go to redmine_git_hosting settings page).

I'll try again next weekend.

**Comment by dosyfier** [comment]
Something worth noticing though: by upgrading rugged lib, I had to add the following option to bundler before running `bundle install`:

```bash
bundle config build.rugged --with-ssh
```

Cf. commit b18ebcf32ef8d8c7d4e3cf01c3fbe85d032a8838.

**Pull request merged**
