### PR TITLE
Update to use jquery tooltips / switch to task_list community fork / Redmine 4.1 support

### PR DESCRIPTION
**Pull request by alexandermeindl**
Update to use jquery tooltips, like redmine 4.1 use it. Changes for latest additionals support.
Use fontawesome for copy-and-paste integration. Drop bootstrap tooltips.

### CODE REVIEW

**Comment by alexandermeindl** [comment]
[task_list](https://github.com/github/task_list) gem was archived in 2016. With switch to the community fork "deckar01-task_list":https://github.com/deckar01/task_list there was fixed problems with markdown code.

**Comment by PowerKiKi** [comment]
FYI, I removed TaskList in https://github.com/jbox-web/redmine_git_hosting/commit/eaa6e5fea661450fecbb2eb2e85343fd1e058028 as a quick fix for Redmine 4.1 compatibility, before seeing this PR. I have nothing against re-adding the community gem, even though I feel it would also be fine to not have it at all.

**Comment by PowerKiKi** [comment]
@alexandermeindl are you still working on this PR ? do you need help for something ?

**Comment by alexandermeindl** [comment]
My PR work some month ago without problems, but you didn't merge it.
I use my fork at the moment, which fixes all reported problems. Some of them are solved with the last merges differently.
At the moment I will use my fork and work on them. So, I suggest we could close this PR.

**Comment by PowerKiKi** [comment]
Oh, I was under the impression that you had write access to this repo and you were going to merge this PR yourself once done. Sorry about that :confused:

Would you be willing to resolve conflicts, so we can merge this once and for all, and we can all use this fork instead ?

**Comment by alexandermeindl** [comment]
Hi,
no problem. At this time, I hadn't write access :/
At the moment I have no time to work on a merge, but I hope this time will come again :)

**Comment by PowerKiKi** [comment]
Sure no stress. When you get to it, feel free to overwrite whatever solution might already exist with yours.

@n-rodriguez I see alexandermeindl as collaborator. Could you please clarify who has access to what ?

image

**Comment by n-rodriguez** [comment]
>  Could you please clarify who has access to what ?

both of you have write access

**Comment by PowerKiKi** [comment]
@alexandermeindl I see you are active on this PR again. Would you be able to merge it ? or shall we overwrite master with this PR ? how do you see the future of your fork and this project ?

**Comment by alexandermeindl** [comment]
Hi @PowerKiKi 
Sure, really want to merge it, but I broke some tests, which I want to fix it before. I do not want do live with my fork for a long time, but I cannot find the time to fix things.

>how do you see the future of your fork and this project ?
- my fork is merged to master
- this projects gets more developer to maintain it and get love in it, again. I see huge amount of time, which was invested by @n-rodriguez - thanks for that!

**Comment by alexandermeindl** [comment]
After playing some  hours with github actions, this folks is automatically tested here: https://github.com/alexandermeindl/redmine_git_hosting/actions
Main task from my perspective now is to fix all crud_controller errors, before we can merge. 
But for the moment a am glad, to see which tests fail :)

**Review by n-rodriguez — COMMENTED** [review]
why? just why?

**Comment by alexandermeindl** [comment]
> > Redmine standard is, archivied data cannot be viewed. This should be valid for repositories, too
> 
> why? just why?

1.  My first reason, you already read. This is the most important for me. Ideally on an archived project, ssh access should be disabled, too
2. a lot of redundant code (all views) copied from Redmine
3. way too dominant link in top menu to archived repos (sure, this would be solvable with other solutions)
4. I never used it and I do not know someone, who wanted to access to archived projects

**Comment by PowerKiKi** [comment]
Reducing the maintenance cost is IMHO a good call, even if it means slightly reducing the feature scope of this project.

**Comment by n-rodriguez** [comment]
Hi there! Any news? I'd love to see it merged :heart:

**Comment by alexandermeindl** [comment]
> Hi there! Any news? I'd love to see it merged ❤️

Hi @n-rodriguez, my plan is to make the merge around christmas - but for sure in this year!

**Comment by alexandermeindl** [comment]
Hi,
I am almost done with it. [Last coding fixes](https://github.com/alexandermeindl/redmine_git_hosting/runs/1596539022?check_suite_focus=true) tomorrow. I think, I can merge tomorrow.

**Comment by n-rodriguez** [comment]
>  I am almost done with it. [Last coding fixes](https://github.com/alexandermeindl/redmine_git_hosting/runs/1596539022?check_suite_focus=true) tomorrow. I think, I can merge tomorrow.

Awesome! :heart:

**Comment by alexandermeindl** [comment]
DONE! Some work for coding standards is open, see https://github.com/jbox-web/redmine_git_hosting/blob/master/.rubocop_todo.yml  (but this is a never ending story).

🎉 🎉 🎉 🎉

**Comment by n-rodriguez** [comment]
You mean : I can merge it? :)

**Comment by PowerKiKi** [comment]
Thank you for your work !

@n-rodriguez will you release it, or shall I do it myself ?

**Comment by alexandermeindl** [comment]
> You mean : I can merge it? :)

Hi @n-rodriguez,
I already merged it. Sorry, if I understood it wrong. I thought, it's ok to do it, because I got commit permissions. But with the switch from Travis to Github Actions, I had some trial and errors to get it to work. So maybe it was better to made the merge to make some fine tuning with it.

**Comment by n-rodriguez** [comment]
> I already merged it.

Great :+1: 

> Sorry, if I understood it wrong.

No problem ;)

**Comment by PowerKiKi** [comment]
@n-rodriguez will you release it, or shall I do it myself ?

**Comment by n-rodriguez** [comment]
> @n-rodriguez will you release it, or shall I do it myself ?

You can do it so you'll see the release process :)

**Comment by PowerKiKi** [comment]
Released as 5.0.0.

Again, thanks for your work, and merry christmas to both of you ! 🎄

**Comment by n-rodriguez** [comment]
> Again, thanks for your work, and merry christmas to both of you ! christmas_tree

@PowerKiKi @alexandermeindl Thank you for your constant work :+1:

**Pull request merged**
